<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function Backup-TeamCityBuildVersion {
    <#
    .SYNOPSIS
    Creates a backup of TeamCity's build version file. This can be useful to know which TeamCity version we need to have on machine where we restore the backup.

    .PARAMETER TeamcityPaths
    Object containing information about TeamCity paths - generated by Get-TeamcityPaths.

    .PARAMETER TeamcityBackupPaths
    Object containing information about backup paths - generated by Get-TeamcityBackupPaths.

    .EXAMPLE
    Backup-TeamCityBuildVersion -TeamcityPaths $TeamcityPaths -TeamcityBackupPaths $TeamcityBackupPaths
    #>

    [CmdletBinding()]
    [OutputType([void])]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityPaths, 
        
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityBackupPaths
    )

    $outputDir = $TeamcityBackupPaths.BaseBackupDir
    [void](New-Item -Path $outputDir -ItemType Directory -Force)
    $buildFile = Get-ChildItem -Path $TeamcityPaths.TeamCityServerDir -Filter "BUILD_*" | Select-Object -ExpandProperty FullName
    if (!$buildFile) {
        throw "Cannot find any BUILD* file in $($TeamcityPaths.TeamCityServerDir)."
    }
    Write-Log -Info "Copying TeamCity build version file: '$buildFile' to '$outputDir'" -Emphasize
    [void](Copy-Item -Path $buildFile -Destination $outputDir -Force)
}