<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function Backup-TeamCityCertificates {
    <#
    .SYNOPSIS
    Creates a backup of TeamCity's JRE certificates. It copies *.cer files available at TC_SERVER\jre directory and creates install_certificates.bat.

    .PARAMETER TeamcityPaths
    Object containing information about TeamCity paths - generated by Get-TeamcityPaths.

    .PARAMETER TeamcityBackupPaths
    Object containing information about backup paths - generated by Get-TeamcityBackupPaths.

    .EXAMPLE
    Backup-TeamCityCertificates -TeamcityPaths $TeamcityPaths -TeamcityBackupPaths $TeamcityBackupPaths
    #>

    [CmdletBinding()]
    [OutputType([void])]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityPaths, 
        
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityBackupPaths
    )

    $outputBackupDir = $TeamcityBackupPaths.CertificatesDir
    [void](New-Item -Path $outputBackupDir -ItemType Directory -Force)
    Write-Log -Info "Creating backup of TeamCity JRE custom certificates." -Emphasize
    $certFilesMask = Join-Path -Path $TeamcityPaths.TeamCityJreDir -ChildPath "\*.cer"
    $certFiles = Get-Item -Path $certFilesMask | Select-Object -ExpandProperty FullName
    if (!$certFiles) {
        Write-Log -Warn "Didn't find any certificate files."
        return
    }
    Write-Log -Info ("Found {0} certificate files - copying." -f $certFiles.Length)
    $keytoolDeleteLine = "bin\keytool -Delete -Noprompt -Keystore lib\security\cacerts -Deststorepass changeit -Alias {0}`r`n"
    $keytoolImportLine= "bin\keytool -Import -Noprompt -Keystore lib\security\cacerts -Deststorepass changeit -Alias {0} -File {1} 2>&1`r`n"
    $keytoolResetErrorLevelAfterDeletionLines = "REM Resetting error level after deletions`r`nver 1>nul`r`n"
    $keytoolBat = ""
    $keytoolBatDeletePart = ""
    $keytoolBatImportPart = ""
    foreach ($certFile in $certFiles) {
        Copy-Item -Path $certFile -Destination $outputBackupDir -Force
        $certFileLeaf = Split-Path -Leaf $certFile
        $alias = $certFileLeaf -replace '.cer$', ''
        $keytoolBatDeletePart += ($keytoolDeleteLine -f $alias)
        $keytoolBatImportPart += ($keytoolImportLine -f $alias, $certFileLeaf)
    }
    $keytoolBat = $keytoolBatDeletePart + $keytoolResetErrorLevelAfterDeletionLines + $keytoolBatImportPart

    Write-Log -Info "Creating install_certificates.bat"
    [void](New-Item -Path (Join-Path -Path $outputBackupDir -ChildPath "install_certificates.bat") -ItemType File -Value $keytoolBat -Force)
}
