<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function Backup-TeamCityAdditionalFiles {
    <#
    .SYNOPSIS
    Creates a backup of TeamCity additional files (plugins, libs, database properties).

    .PARAMETER TeamcityPaths
    Object containing information about TeamCity paths - generated by Get-TeamcityPaths.

    .PARAMETER TeamcityBackupPaths
    Object containing information about backup paths - generated by Get-TeamcityBackupPaths.

    .EXAMPLE
    Backup-TeamCityAdditionalFiles -TeamcityPaths $TeamcityPaths -TeamcityBackupPaths $TeamcityBackupPaths
    #>

    [CmdletBinding()]
    [OutputType([void])]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityPaths, 
        
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityBackupPaths
    )

    [void](New-Item -Path $TeamcityBackupPaths.DatabasePropertiesDir -ItemType Directory -Force)
    Write-Log -Info "Creating backup of database properties" -Emphasize
    $filesToCopy = Join-Path -Path $TeamcityPaths.TeamCityConfigDir -ChildPath "database.*properties*"
    Copy-Item -Path $filesToCopy -Destination $TeamcityBackupPaths.DatabasePropertiesDir -Force

    [void](New-Item -Path $TeamcityBackupPaths.ServerConfigDir -ItemType Directory -Force)
    Write-Log -Info "Creating backup of server.xml" -Emphasize
    $filesToCopy = Join-Path -Path $TeamcityPaths.teamCityServerDir -ChildPath "conf\server.xml"
    Copy-Item -Path $filesToCopy -Destination $TeamcityBackupPaths.ServerConfigDir -Force

    [void](New-Item -Path $TeamcityBackupPaths.PluginsDir -ItemType Directory -Force)
    $currentTimestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $outputPluginsFile = Join-Path -Path $TeamcityBackupPaths.PluginsDir -ChildPath "TeamCity_plugins_$currentTimestamp"
    Write-Log -Info "Creating backup of TeamCity plugins" -Emphasize
    Compress-With7Zip -PathsToCompress $TeamcityPaths.TeamCityPluginsRelativeDir -OutputFile $outputPluginsFile -WorkingDirectory $TeamcityPaths.TeamCityDataDir

    [void](New-Item -Path $TeamcityBackupPaths.LibsDir -ItemType Directory -Force)
    $outputLibFile = Join-Path -Path $TeamcityBackupPaths.LibsDir -ChildPath "TeamCity_libs_$currentTimestamp"
    Write-Log -Info "Creating backup of TeamCity libs" -Emphasize
    Compress-With7Zip -PathsToCompress $TeamcityPaths.TeamCityLibsRelativeDir -OutputFile $outputLibFile -WorkingDirectory $TeamcityPaths.TeamCityDataDir

    [void](New-Item -Path $TeamcityBackupPaths.JreDir -ItemType Directory -Force)
    $outputJreFile = Join-Path -Path $TeamcityBackupPaths.JreDir -ChildPath "TeamCity_jre_$currentTimestamp"
    Write-Log -Info "Creating backup of TeamCity JRE." -Emphasize
    Compress-With7Zip -PathsToCompress $TeamcityPaths.TeamCityJreDir -OutputFile $outputJreFile -WorkingDirectory $TeamcityPaths.TeamCityServerDir
}