<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function New-TeamCityFinalBackupFile {
    <#
    .SYNOPSIS
    Creates a final TeamCity backup file, consisting of all partial backups (New-TeamCity*Backup) and deletes temporary directory.

    .PARAMETER TeamcityPaths
    Object containing information about TeamCity paths - generated by Get-TeamcityPaths.

    .PARAMETER BackupTempDir
    Source temporary directory.

    .PARAMETER OutputBackupDir
    Destination directory.

    .PARAMETER Password
    PSCredential object that stores the password used to encrypt the archive.

    .EXAMPLE
    New-TeamCityFinalBackupFile -TeamcityPaths $TeamcityPaths -BackupTempDir $outputBackupTempDir -OutputBackupDir $OutputBackupDir -Password $Password
    #>

    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityPaths, 
        
        [Parameter(Mandatory=$true)]
        [string] 
        $BackupTempDir,

        [Parameter(Mandatory=$true)]
        [string] 
        $OutputBackupDir,

        [Parameter(Mandatory=$true)]
        [System.Management.Automation.PSCredential] 
        $Password
    )

    $currentTimestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $hostname = hostname
    $outputFile = Join-Path -Path $OutputBackupDir -ChildPath "TeamCity_${hostname}_${currentTimestamp}.zip"
    Write-Log -Info "Packaging '$BackupTempDir to '$outputFile' "
    Compress-With7Zip -PathsToCompress (Join-Path -Path $BackupTempDir -ChildPath "*") -OutputFile $outputFile -CompressionLevel "fast" -Password $Password

    if (!(Test-Path -Path $outputFile)) {
        Write-Log -Critical "Backup failed - no final backup output file: '$outputFile'"
    }
    
    Write-Log -Info "Backup file '$outputFile' created successfully." -Emphasize
    return $outputFile
}