<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function Restore-TeamCityRestBackup {
    <#
    .SYNOPSIS
    Restores TeamCity from REST backup, using maintainDB utility as described at http://confluence.jetbrains.com/display/TCD8/Restoring+TeamCity+Data+from+Backup.

    .PARAMETER TeamcityPaths
    Object containing information about TeamCity paths - generated by Get-TeamcityPaths.

    .PARAMETER TeamcityBackupPaths
    Object containing information about backup paths - generated by Get-TeamcityBackupPaths.

    .PARAMETER DatabasePropertiesFile
    Path to database.properties file. Can be empty if connection stored in backup should be used. See Get-TeamCityRestorePlan for details.

    .PARAMETER RestoreToInternalDatabase
    If true, restore will be made to the internal database (hsqldb). See Get-TeamCityRestorePlan for details.

    .EXAMPLE
    Restore-TeamCityRestBackup -TeamcityPaths $TeamcityPaths -TeamcityBackupPaths $TeamcityBackupPaths -DatabasePropertiesFile $DatabasePropertiesFile -RestoreToInternalDatabase:$RestoreToInternalDatabase
    #>

    [CmdletBinding()]
    [OutputType([void])]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityPaths, 
        
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityBackupPaths,
        
        [Parameter(Mandatory=$false)]
        [string] 
        $DatabasePropertiesFile,

        [Parameter(Mandatory=$false)]
        [switch] 
        $RestoreToInternalDatabase
    )

    $backupFile = Get-LastBackupFileFromDirectory -Dir $TeamcityBackupPaths.RestBackupDir
    $teamCityBackupDir = $TeamcityPaths.TeamCityBackupDir
    if (!(Test-Path -LiteralPath $teamCityBackupDir)) {
        Write-Log -Info "Creating directory '$teamCityBackupDir'."
        [void](New-Item -Path $teamCityBackupDir -ItemType directory -Force)
    }
    Write-Log -Info "Copying backup file $backupFile' to '$teamCityBackupDir'"
    [void](Copy-Item -Path $backupFile -Destination $teamCityBackupDir -Force)
    
    $backupFile = Split-Path -Leaf $backupFile
    $maintainDbCmd = Join-Path -Path $TeamcityPaths.TeamCityServerDir -ChildPath "bin\maintainDB.cmd"  
    $maintainDbCommand += ("{0} restore -F {1}" -f (Add-QuotesToPaths $maintainDbCmd, $backupFile))

    $dbPropsFile = $null
    if ($RestoreToInternalDatabase) {
        $dbPropsFile = (Join-Path -Path $TeamcityBackupPaths.DatabasePropertiesDir -ChildPath "database.hsqldb.properties.dist")
    } elseif ($DatabasePropertiesFile) {
        $dbPropsFile = $DatabasePropertiesFile
    } else {
        $dbPropsFile = (Join-Path -Path $TeamcityBackupPaths.DatabasePropertiesDir -ChildPath "database.properties")
    }

    if (!(Test-Path -LiteralPath $dbPropsFile)) {
        Write-Log -Critical "Cannot access file '$dbPropsFile'. Please create the file manually and run restore with -DatabasePropertiesFile."
    }


    if ($dbPropsFile) {
        $maintainDbCommand += (" -T {0}" -f (Add-QuotesToPaths -Paths $dbPropsFile))
    }
    
    Write-Log -Info "Restoring TeamCity backup file '$backupFile'" -Emphasize
    [void](Invoke-ExternalCommand -Command $maintainDbCommand)
}