<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function Restore-TeamCityEnvironmentVariables {
    <#
    .SYNOPSIS
    Restores TeamCity environment variables from backup.

    .PARAMETER TeamcityBackupPaths
    Object containing information about backup paths - generated by Get-TeamcityBackupPaths.

    .EXAMPLE
    Restore-TeamCityEnvironmentVariables -TeamcityBackupPaths $TeamcityBackupPaths
    #>

    [CmdletBinding()]
    [OutputType([void])]
    param(       
        [Parameter(Mandatory=$true)]
        [PSCustomObject] 
        $TeamcityBackupPaths
    )

    $backupDir = $TeamcityBackupPaths.EnvDir
    $envVarsFile = Join-Path -Path $backupDir -ChildPath "envVars.txt"
    if (!(Test-Path -LiteralPath $envVarsFile)) {
        Write-Log -Warn "No TEAMCITY environment variables file at '$envVarsFile'. You will need to set TEAMCITY_SERVER_MEM_OPTS manually (according to TeamCity documentation)."
        Request-UserInputToContinue
        return
    }
    $envVars = ConvertFrom-Json -InputObject (Get-Content -Path $envVarsFile -ReadCount 0 | Out-String)
    foreach ($envVar in $envVars) {
        Write-Log -Info "Setting environment variable '$($envVar.Key)' to '$($envVar.Value)'" -Emphasize
        [Environment]::SetEnvironmentVariable($envVar.Key, $envVar.Value, "Machine")
    }
    Update-EnvironmentVariables
}